# Generated by Django 5.0.6 on 2025-08-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fooditem_remove_profile_profile_pic_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='step_number',
            new_name='recipes',
        ),
    ]
