# Generated by Django 5.2.7 on 2025-12-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fooditem_remove_profile_profile_pic_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
