# Generated by Django 5.0.6 on 2025-08-03 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
