# Generated by Django 5.0.6 on 2025-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fooditem_iamge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
