# Generated by Django 5.0.6 on 2025-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fooditem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='iamge',
            new_name='image',
        ),
    ]
