# Generated by Django 5.0.6 on 2025-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_iamge_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='fav_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
