# Generated by Django 5.2.5 on 2025-08-28 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_favorites_fav_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='food_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
