# Generated by Django 5.2.5 on 2025-08-28 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_fooditem_audio_fooditem_audio1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='audio1',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='audio2',
        ),
        migrations.AddField(
            model_name='recipe',
            name='audio1',
            field=models.FileField(blank=True, null=True, upload_to='food_audio1/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='audio2',
            field=models.FileField(blank=True, null=True, upload_to='food_audio2/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
